### ISSUE TITLE
Image not Downloading

### ISSUE THREAD

**Issue by CoderAnsh694** [1s0n/Mangareader-Downloader-v2#10]
The Program only saves the images with the logo of MangaReader and the text with it, not the manga page. I tried loading the complete manga then trying, but still the same result. I have full internet access.
![Screenshot 2024-01-07 205450](https://github.com/1s0n/Mangareader-Downloader-v2/assets/83581743/26abab0a-77cc-4821-8003-b591dff863f2)

**Comment by 1s0n** [comment]
I've recently fixed this issue, it should work if you redownload the code. I have just tested it with your specific manga
