### ISSUE TITLE
Lots of Retrying on some URLs

### ISSUE THREAD

**Issue by UnionAdmin2286** [1s0n/Mangareader-Downloader-v2#17]
at https://mangareader.to/read/vinland-saga-14/en/volume-1.   the retry gets stuck at page 46.   i'll update this if it fixes itself

Update:  it fixed itself,  after about 50-60 retry's  but im keeping this open to let you know about the large number of retries.  any idea whats causing this?

**Comment by 1s0n** [comment]
It's probably either bad wifi, or a rate limit put in by mangareader.to

**Comment by UnionAdmin2286** [comment]
ok then.  thanks for the quick reply.  also,  could you please update the batch file by putting "import os" at the top.  it doesn't operate otherwise
