### ISSUE TITLE
[macOS] Error Not a directory: 'temp/.DS_Store'

### ISSUE THREAD

**Issue by 4b15ed24f576** [1s0n/Mangareader-Downloader-v2#3]
**Error:**

Got this error at some point when trying to run "python3 stitcher.py":

`NotADirectoryError: [Errno 20] Not a directory: 'temp/.DS_Store'`

In this specific case, the error is caused by the file named ".DS_Store" within the "temp" directory. The ".DS_Store" file is a hidden file created by macOS Finder to store metadata about the folder's view settings. Somehow I couldn't display the ".DS_Store file" even when displaying hidden files in the Finder.

**Fix:**

Run this command to delete the .DS_Store file:

`rm temp/.DS_Store`

Should work back to normal :-)

**Comment by 1s0n** [comment]
Thanks, I'll add code in the stitcher to check if its a directory.

**Comment by 1s0n** [comment]
Should work now
