### ISSUE TITLE
All files downloaded are the website's logo

### ISSUE THREAD

**Issue by Diegoafv** [1s0n/Mangareader-Downloader-v2#8]
Tried with many different URLs, it seems to download to the correct folder, with the correct title, but all the files received are the mandareader.to logo, all the same.

![image_2023-12-23_230258866](https://github.com/1s0n/Mangareader-Downloader-v2/assets/29114966/6d3db851-8f9e-4fd3-9caa-8de2f2c5c14a)

**Comment by 3vil3vo** [comment]
@Diegoafv 
open the downloader.py file with an code/text editor 
![image](https://github.com/1s0n/Mangareader-Downloader-v2/assets/141663847/fab4660f-c488-406c-8d87-7fbc1af50f87)
then find this line (line 36):
![image](https://github.com/1s0n/Mangareader-Downloader-v2/assets/141663847/42784d6f-644c-43f7-aa54-640c9053f517)
and replace the 1 with 0:
![image](https://github.com/1s0n/Mangareader-Downloader-v2/assets/141663847/71b8cb15-a252-4ad5-981a-47f61ccb1b97)

**Comment by 1s0n** [comment]
Sorry for the delay, I have fixed this.
