### ISSUE TITLE
Error FileNotFoundError

### ISSUE THREAD

**Issue by alisanbox** [1s0n/Mangareader-Downloader-v2#9]
i installed Pyton 3.12.1 64 bit on windows 10 64 bit
then using command prompt "pip3 install -r requirements.txt" Done (installing, no error)
run "main.py" giving error

> C:\Python312\Scripts\Mangareader-Downloader-v2-master>main.py
Traceback (most recent call last):
  File "C:\Python312\Scripts\Mangareader-Downloader-v2-master\main.py", line 12, in <module>
    chromepath = chromedriver_autoinstaller.install()
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\chromedriver_autoinstaller\__init__.py", line 21, in install
    chromedriver_filepath = utils.download_chromedriver(path, no_ssl)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\chromedriver_autoinstaller\utils.py", line 269, in download_chromedriver
    chrome_version = get_chrome_version()
                     ^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\site-packages\chromedriver_autoinstaller\utils.py", line 166, in get_chrome_version
    dirs = [f.name for f in os.scandir("C:\\Program Files\\Google\\Chrome\\Application") if f.is_dir() and re.match("^[0-9.]+$", f.name)]
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files\\Google\\Chrome\\Application'

**Comment by 1s0n** [comment]
Make sure you have chrome installed to the default location, and try again. Because it seems that the chromedriver_autoinstaller cannot find local chrome installed.

**Comment by alisanbox** [comment]
wow, thanks, it works, 
after checking my chrome location, it's at : 
`C:\Program Files (x86)\Google\Chrome\Application`
so i create folder at 
`C:\Program Files\Google\Chrome\Application`
and put shortcut of `chrome.exe`, This Works
main.py works well, Nice ! Thank you

next trying `batch.py`, there's error

> C:\Python312\Scripts\Mangareader-Downloader-v2-master>batch.py
ENTER URL: https://mangareader.to/read/the-brilliant-healers-new-life-in-the-shadows-67659/en/chapter-1
Traceback (most recent call last):
  File "C:\Python312\Scripts\Mangareader-Downloader-v2-master\batch.py", line 2, in <module>
    startVol = int(url.split("volume-")[1])
                   ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

i tried with different title & chapter 2, but same error
any idea what's the error about?
thx before

**Comment by 1s0n** [comment]
the batch downloader could only download volumes, I will fix it

**Comment by 1s0n** [comment]
It should be fixed now, I will add better support for downloading chapters once I finish the gui.

**Comment by alisanbox** [comment]
Yes, thank you, it works great
